language: c

compiler:
  - gcc


addons:
  apt:
    packages:
      - valgrind
      - cppcheck
      - make
      - cmake
      - lcov
      - doxygen
      - help2man

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
